name: Build PDFs of UML-Diagramms
on:
  [push]
   # paths:
    #  - doc/*.uxf
jobs:
  umlet_uxf2pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - name: Download umlet
        run: wget https://www.umlet.com/download/umlet_15_1/umlet-standalone-15.1.zip -O umlet.zip
      - name: Unzip
        run: unzip umlet.zip
      - name: Ordner
        run: mkdir doc_pdf
      - name: Run
        run: java -jar Umlet/umlet.jar -action=convert -format=pdf -filename=doc/*.uxf -output=doc_pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: doc_pdf
          path: doc_pdf/*.pdf

      - name: Checkout Thesis
        uses: actions/checkout@v4
        with:
          repository: FlorianTimm/PhotoBox_Thesis
          path: thesis
          sparsecheckout: img/uml
      - name: Copy
        run: mv doc_pdf/*.pdf thesis/img/uml/
            - name: Upload PDF file
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: thesis
      
        
