name: Build PDFs of UML-Diagramms
on:
  [push]
   # paths:
    #  - doc/*.uxf
jobs:
  umlet_uxf2pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - name: Download umlet
        run: wget https://www.umlet.com/download/umlet_15_1/umlet-standalone-15.1.zip -O umlet.zip
      - name: Unzip
        run: unzip umlet.zip
      - name: Ordner
        run: mkdir doc_pdf
      - name: Run
        run: java -jar Umlet/umlet.jar -action=convert -format=pdf -filename=doc/*.uxf -output=doc_pdf
      - name: Push to Thesis
        uses: markjivko/push-to-github@main
        env:
          GITHUB_SSH_KEY: ${{ secrets.THESIS_PRIVATE_SSH_KEY }}
        with:
          source-directory: "doc_pdf"
          target-github-username: "FlorianTimm"
          target-github-repository: "PhotoBox_Thesis"
          target-github-branch: "main"
          target-directory: "thesis/img/uml"
          commit-message: ${{ github.event.head_commit.message }}
      
        
